<?php

namespace Database\Seeders;

use App\Models\ZabbixDevice;
use Illuminate\Database\Seeder;

/**
 * Seeds the Zabbix device list that used to be hardcoded in the two Blade
 * components (issue #698). Rows are copied verbatim from the pre-refactor
 * `it/networks` and `it/wireless` arrays — do not retype item IDs by hand.
 */
class ZabbixDeviceSeeder extends Seeder
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public static function rows(): array
    {
        return [
            [
                'type' => 'network',
                'name' => 'فیبر اصلی',
                'out_item_id' => '73638',
                'in_item_id' => '73494',
                'initial_duration' => 7200,
                'sort_order' => 0,
            ],
            [
                'type' => 'network',
                'name' => 'a سویچ',
                'out_item_id' => '77146',
                'in_item_id' => '76954',
                'initial_duration' => 7200,
                'sort_order' => 1,
            ],
            [
                'type' => 'network',
                'name' => 'b سویچ',
                'out_item_id' => '77154',
                'in_item_id' => '76962',
                'initial_duration' => 7200,
                'sort_order' => 2,
            ],
            [
                'type' => 'network',
                'name' => 'c سویچ',
                'out_item_id' => '77150',
                'in_item_id' => '76958',
                'initial_duration' => 7200,
                'sort_order' => 3,
            ],
            [
                'type' => 'network',
                'name' => 'e سویچ',
                'out_item_id' => '77178',
                'in_item_id' => '76986',
                'initial_duration' => 7200,
                'sort_order' => 4,
            ],
            [
                'type' => 'network',
                'name' => 'f سویچ',
                'out_item_id' => '73649',
                'in_item_id' => '73505',
                'initial_duration' => 7200,
                'sort_order' => 5,
            ],
            [
                'type' => 'network',
                'name' => 'صائین هیدج عمید',
                'out_item_id' => '74763',
                'in_item_id' => '74610',
                'initial_duration' => 7200,
                'sort_order' => 6,
            ],
            [
                'type' => 'network',
                'name' => 'هفده شهریور',
                'out_item_id' => '74794',
                'in_item_id' => '74641',
                'initial_duration' => 7200,
                'sort_order' => 7,
            ],
            [
                'type' => 'network',
                'name' => 'مرکز 5',
                'out_item_id' => '74798',
                'in_item_id' => '74645',
                'initial_duration' => 7200,
                'sort_order' => 8,
            ],
            [
                'type' => 'network',
                'name' => 'قروه شریف درسجین',
                'out_item_id' => '74799',
                'in_item_id' => '74646',
                'initial_duration' => 7200,
                'sort_order' => 9,
            ],
            [
                'type' => 'network',
                'name' => 'شناط',
                'out_item_id' => '74771',
                'in_item_id' => '74618',
                'initial_duration' => 7200,
                'sort_order' => 10,
            ],
            [
                'type' => 'network',
                'name' => 'بهورزی',
                'out_item_id' => '74797',
                'in_item_id' => '74644',
                'initial_duration' => 7200,
                'sort_order' => 11,
            ],
            [
                'type' => 'network',
                'name' => 'دانشکده',
                'out_item_id' => '74802',
                'in_item_id' => '74649',
                'initial_duration' => 7200,
                'sort_order' => 12,
            ],
            [
                'type' => 'network',
                'name' => 'خرم دره',
                'out_item_id' => '74767',
                'in_item_id' => '74614',
                'initial_duration' => 7200,
                'sort_order' => 13,
            ],
            [
                'type' => 'network',
                'name' => 'بیمارستان الغدیر',
                'out_item_id' => '74770',
                'in_item_id' => '74617',
                'initial_duration' => 7200,
                'sort_order' => 14,
            ],
            [
                'type' => 'network',
                'name' => 'بیمارستان امدادی',
                'out_item_id' => '73647',
                'in_item_id' => '73503',
                'initial_duration' => 7200,
                'sort_order' => 15,
            ],
            [
                'type' => 'network',
                'name' => 'وایرلس هیدج',
                'out_item_id' => '71639',
                'in_item_id' => '71648',
                'initial_duration' => 7200,
                'sort_order' => 16,
            ],
            [
                'type' => 'network',
                'name' => 'وایرلس صائین قلعه',
                'out_item_id' => '71439',
                'in_item_id' => '71448',
                'initial_duration' => 7200,
                'sort_order' => 17,
            ],
            [
                'type' => 'network',
                'name' => 'اشتراک',
                'out_item_id' => '77153',
                'in_item_id' => '76961',
                'initial_duration' => 7200,
                'sort_order' => 18,
            ],
            [
                'type' => 'network',
                'name' => 'آی تی یک',
                'out_item_id' => '77186',
                'in_item_id' => '76994',
                'initial_duration' => 7200,
                'sort_order' => 19,
            ],
            [
                'type' => 'network',
                'name' => 'آی تی سه',
                'out_item_id' => '77171',
                'in_item_id' => '76979',
                'initial_duration' => 7200,
                'sort_order' => 20,
            ],
            [
                'type' => 'network',
                'name' => 'هایپر یک',
                'out_item_id' => '77169',
                'in_item_id' => '76977',
                'initial_duration' => 7200,
                'sort_order' => 21,
            ],
            [
                'type' => 'network',
                'name' => 'هایپر دو',
                'out_item_id' => '77184',
                'in_item_id' => '76992',
                'initial_duration' => 7200,
                'sort_order' => 22,
            ],
            [
                'type' => 'network',
                'name' => 'هایپر سه',
                'out_item_id' => '77164',
                'in_item_id' => '76972',
                'initial_duration' => 7200,
                'sort_order' => 23,
            ],
            [
                'type' => 'network',
                'name' => 'پایش',
                'out_item_id' => '77155',
                'in_item_id' => '76963',
                'initial_duration' => 7200,
                'sort_order' => 24,
            ],
            [
                'type' => 'wireless',
                'name' => 'اعلایی',
                'signal_item_id' => '75297',
                'frequency_item_id' => '71725',
                'response_item_id' => '70996',
                'min' => -85,
                'max' => -45,
                'sort_order' => 0,
            ],
            [
                'type' => 'wireless',
                'name' => '17 شهریور',
                'signal_item_id' => '75231',
                'frequency_item_id' => '71713',
                'response_item_id' => '71055',
                'min' => -85,
                'max' => -45,
                'sort_order' => 1,
            ],
            [
                'type' => 'wireless',
                'name' => 'شناط',
                'signal_item_id' => '75470',
                'frequency_item_id' => '69540',
                'response_item_id' => '69426',
                'min' => -85,
                'max' => -45,
                'sort_order' => 2,
            ],
            [
                'type' => 'wireless',
                'name' => 'شریف آباد',
                'signal_item_id' => '75477',
                'frequency_item_id' => '72019',
                'response_item_id' => '71831',
                'min' => -85,
                'max' => -45,
                'sort_order' => 3,
            ],
            [
                'type' => 'wireless',
                'name' => 'صائین قلعه',
                'signal_item_id' => '75440',
                'frequency_item_id' => '71719',
                'response_item_id' => '70937',
                'min' => -85,
                'max' => -45,
                'sort_order' => 4,
            ],
            [
                'type' => 'wireless',
                'name' => 'مرکز5',
                'signal_item_id' => '75418',
                'frequency_item_id' => '71246',
                'response_item_id' => '70577',
                'min' => -85,
                'max' => -45,
                'sort_order' => 5,
            ],
            [
                'type' => 'wireless',
                'name' => 'هیدج',
                'signal_item_id' => '75425',
                'frequency_item_id' => '71266',
                'response_item_id' => '70701',
                'min' => -85,
                'max' => -45,
                'sort_order' => 6,
            ],
            [
                'type' => 'wireless',
                'name' => 'حسین آباد',
                'signal_item_id' => '75447',
                'frequency_item_id' => '71707',
                'response_item_id' => '71173',
                'min' => -85,
                'max' => -45,
                'sort_order' => 7,
            ],
            [
                'type' => 'wireless',
                'name' => 'عمید آباد',
                'signal_item_id' => '75312',
                'frequency_item_id' => '71261',
                'response_item_id' => '70760',
                'min' => -85,
                'max' => -45,
                'sort_order' => 8,
            ],
            [
                'type' => 'wireless',
                'name' => 'ارغوان',
                'signal_item_id' => '75335',
                'frequency_item_id' => '71735',
                'response_item_id' => '70819',
                'min' => -85,
                'max' => -45,
                'sort_order' => 9,
            ],
            [
                'type' => 'wireless',
                'name' => 'بهورزی',
                'signal_item_id' => '75342',
                'frequency_item_id' => '71251',
                'response_item_id' => '70518',
                'min' => -85,
                'max' => -45,
                'sort_order' => 10,
            ],
            [
                'type' => 'wireless',
                'name' => 'درسجین',
                'signal_item_id' => '75357',
                'frequency_item_id' => '72009',
                'response_item_id' => '71949',
                'min' => -85,
                'max' => -45,
                'sort_order' => 11,
            ],
            [
                'type' => 'wireless',
                'name' => 'دکل قروه',
                'signal_item_id' => '75380',
                'frequency_item_id' => '70165',
                'response_item_id' => '70098',
                'min' => -85,
                'max' => -45,
                'sort_order' => 12,
            ],
            [
                'type' => 'wireless',
                'name' => 'قروه',
                'signal_item_id' => '75395',
                'frequency_item_id' => '72014',
                'response_item_id' => '71890',
                'min' => -85,
                'max' => -45,
                'sort_order' => 13,
            ],
        ];
    }

    public function run(): void
    {
        foreach (self::rows() as $row) {
            ZabbixDevice::query()->firstOrCreate([
                'type' => $row['type'],
                'name' => $row['name'],
            ], $row);
        }
    }
}
