APP_NAME=h-dashboard
APP_ENV=local
APP_KEY=base64:aelQP/iruUmruqDr1iZ9XEFB/EgFm3crvwHN1lqnix8=
APP_DEBUG=false
APP_URL=http://127.0.0.1:8000
# ── Map / routing / geocoding servers ──
# تایل/نقشه (OpenStreetMap)
TILE_SERVER_IP=tile.openstreetmap.org
TILE_SERVER_PORT=
TILE_SERVER_SCHEME=https
# قالب کامل آدرس تایل (OSM)
TILE_URL_TEMPLATE=https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
# مسیریابی (OSRM)
ROUTING_SERVER_IP=127.0.0.1
ROUTING_SERVER_PORT=5000
ROUTING_SERVER_SCHEME=http
# آدرس‌یابی (Nominatim)
GEOCODING_SERVER_IP=127.0.0.1
GEOCODING_SERVER_PORT=8088
GEOCODING_SERVER_SCHEME=http

APP_LOCALE=fa
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=h_dashboard
DB_USERNAME=h_dashboard
DB_PASSWORD=example_6162e0f827d119b0
DB_ROOT_PASSWORD=example_4be97a3608e27da3
DB_DEFAULT_EMAIL=admin@...
DB_DEFAULT_PASSWORD=example_eb4bddfe0a613c1e

# Application timezone (display layer). PostgreSQL keeps UTC for storage;
# convert to Tehran/Jalali in code via morilog/jalali & hekmatinasser/verta.
APP_TIMEZONE=Asia/Tehran

SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_SECURE_COOKIE=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local


# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

#REDIS_CLIENT=phpredis


# MAIL_MAILER=log
# MAIL_SCHEME=null
# MAIL_HOST=127.0.0.1
# MAIL_PORT=2525
# MAIL_USERNAME=null
# MAIL_PASSWORD=null
# MAIL_FROM_ADDRESS="hello@example.com"
# MAIL_FROM_NAME="${APP_NAME}"

# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_DEFAULT_REGION=us-east-1
# AWS_BUCKET=
# AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"
VITE_HOST=localhost
VITE_PORT=5173
#OCTANE_SERVER=frankenphp

CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_CONNECTION=redis

REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=example_e317eb5b0fd7e85c

ZABBIX_URL=http://127.0.0.1:8443/api_jsonrpc.php
ZABBIX_TOKEN=
